name: Documentation
on:
  push:
    branches:
      - Documentation
permissions:
  contents: write
jobs:
  Doc:
    name: Doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Generate Doc
        run: mvn -B javadoc::javadoc
      - name: Deploy Doc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs